### ISSUE TITLE
El cuadro de diálogo no cerraba...

### ISSUE THREAD

**Issue by MARSFOREVER472** [MARSFOREVER472/Data#3]
_...el único problema que hubo fue que yo he creado los 2 formularios para vincularlos entre sí, sin embargo el cuadro de diálogo del segundo formulario no cerraba correctamente._

**Comment by Autinfit** [comment]
_Estimado, si es que tienes un problema, lo más probable es que al segundo formulario deberías en la esquina inferior derecha de la solución editarlo de manera estática en la sección DialogResult, dejarlo en OK en vez de la opción None por defecto.

Espero que te sirva de ayuda para solucionar este inconveniente._

**Comment by Autinfit** [comment]
Estimado, si es que tienes un problema, lo más probable es que al segundo formulario deberías en la esquina inferior derecha de la solución editarlo de manera estática en la sección DialogResult, dejarlo en OK en vez de la opción None por defecto.

Espero que te sirva de ayuda para solucionar este inconveniente.

**Comment by MARSFOREVER472** [comment]
**Gracias, estimado, ahora logré resolver este inconveniente, realmente me funcionó.**
