### ISSUE TITLE
Logré funcionar todo lo demás, pero...

### ISSUE THREAD

**Issue by MARSFOREVER472** [MARSFOREVER472/Data#9]
Había otro percance que era la edición de los tamaños del archivo elegido en un "PictureBox" del formulario 1, si es que mi compañero organizador me puede solicitar ayuda, por favor!!!!

Muchas Gracias!!!!

**Comment by Autinfit** [comment]
Es súper sencillo, si se ve mal la imagen del archivo elegido es que debería elegir el modo de tamaño de la imagen dentro de las propiedades de este formulario asociado, que está al lado derecho inferior de la solución, ya que, en vez de dejarlo normal o en otro modo, deberías centrarlo si es que tendrías un tamaño adecuado para esto.

**Comment by MARSFOREVER472** [comment]
Muchas gracias, estimado, arreglaré este inconveniente!!!!!

Saludos!!!!
